spring.application.name=TourDeFrance
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/tourdefrance
spring.datasource.username=root
spring.datasource.password=cotxEx-xywryx-vijke3

spring.jpa.hibernate.ddl-auto=create-drop
